### ISSUE TITLE
Latest docs not in this repo

### ISSUE THREAD

**Issue by iconara** [awsdocs/amazon-athena-user-guide#12]
I want to help improve the docs, but the latest docs are not in this repo. If I click "Edit on GitHub" on any of the pages about views I just get a 404 (try https://docs.aws.amazon.com/athena/latest/ug/when-to-use-views.html that points to https://github.com/awsdocs/amazon-athena-user-guide/tree/master/doc_source/when-to-use-views.md, for example).

**Comment by JuliaMalkin** [comment]
Hello Theo,
Thank you for your comment. You are correct, the documentation on views is not yet pushed to this repository, we are in the process of addressing this issue later today. You will then be able to create pull requests. Please check in later today or comment here and I will be sure to follow up on your suggestions and fixes!

**Comment by JuliaMalkin** [comment]
I updated the docs on GitHub so you can now create pull requests against the newly added content. Thank you.

**Comment by iconara** [comment]
@JuliaMalkin thank you for updating!
