### ISSUE TITLE
Help wanted: examples of setting up Glue Crawler to work with Athena (folder structure)

### ISSUE THREAD

**Issue by JuliaMalkin** [awsdocs/amazon-athena-user-guide#16]
Hello dear community,
We know from this documentation https://docs.aws.amazon.com/en_us/athena/latest/ug/glue-best-practices.html#schema-crawlers-data-sources, that:
"When an AWS Glue crawler scans Amazon S3 and detects multiple directories, it uses a heuristic to determine where the root for a table is in the directory structure, and which directories are partitions for the table. In some cases, where the schema detected in two or more directories is similar, the crawler may treat them as partitions instead of separate tables. One way to help the crawler discover individual tables is to add each table's root directory as a data store for the crawler. "
Often, many of us who use Athena with Glue, need to know how to set up folders, so that the integration with the Amazon Glue Crawler works seamlessly. If you've tackled this, and have a recommendation, please share and help! Much appreciate.

**Comment by waynetaylor** [comment]
Hi Julian, are you just looking for examples of the folder structure and partitioning? 

At gogo, we use partitioning of all our data into year=xxxx/month=xx/year=xx and output to parquet. We then have crawlers setup to run via a custom cron like schedule to update the metastore for athena querying.

**Comment by JuliaMalkin** [comment]
Thank you, Amit, for your tips! A few questions: in what use cases is it useful to use your tip #2?
Also, regarding your point in #3, what is the reason for noting it? Is it to help users know how best to deal with schema updates when the crawler runs again? Other?

**Comment by JuliaMalkin** [comment]
@waynetaylor  thank you replying. 
>>>are you just looking for examples of the folder structure and partitioning?
I am looking for examples of the folder structure/setting up the Glue crawler that allows it to treat the discovered tables as separate tables and not as partitions within a single table.

**Comment by JuliaMalkin** [comment]
Closing as I have received some feedback on this.
