### ISSUE TITLE
Incorrect Documentation for ignore.malformed.json

### ISSUE THREAD

**Issue by geojins** [awsdocs/amazon-athena-user-guide#22]
Hi,
Option _ignore.malformed.json_ is applicable only for Openx JSON Serde. However in the documentation, it is 
given as an option for Hive JSON SerDe. 

https://docs.aws.amazon.com/athena/latest/ug/json.html#hivejson

**Comment by JuliaMalkin** [comment]
Hello George,
thank you for pointing this out! I will address this issue shortly. Please let us know if you notice any other issues that must be fixed, I value your feedback.

**Comment by JuliaMalkin** [comment]
Hi,
I have just updated the documentation. Closing and thank you for letting us know!!
