### ISSUE TITLE
Compression formats: Firehose compatibility correction

### ISSUE THREAD

**Issue by adamt06** [awsdocs/amazon-athena-user-guide#29]
Currently, compression-formats.md says:
> Use the GZIP compression in Athena for querying Amazon Kinesis Data Firehose logs. Athena and Amazon Kinesis Data Firehose each support different versions of SNAPPY, so GZIP is the only compatible format.

This seems to be incorrect. We are using ORC files with Snappy compression in Firehose and Athena can read it. Not sure if it applies to Parquet as well though.

**Comment by Pahtoe** [comment]
@adamt06 Thanks for the feedback and the callout on the error. We'll do a bit of research on our end and get this fixed in an upcoming doc push. Sorry for the excruciatingly long delay responding; we were down a writer for a while in EMR but are staffed back up now. Thanks again!

**Comment by taammann** [comment]
Doc has been updated. Thanks!
