### ISSUE TITLE
Add Partitioning config for cloudtrail logs

### ISSUE THREAD

**Issue by FireballDWF** [awsdocs/amazon-athena-user-guide#33]
https://github.com/awsdocs/amazon-athena-user-guide/blob/master/doc_source/cloudtrail-logs.md#create-cloudtrail-table should include the following performance improvement by adding Partitioning:
```
PARTITIONED BY (region string, year string, month string, day string)
```

**Comment by taammann** [comment]
Thanks, FireballDWF - we'll add that to the documentation.
