### ISSUE TITLE
Getting started misses the workgroup needed information

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-athena-user-guide#36]
I may be missing something so I still create the issue to avoid forgetting about it.

I believe the Getting Started guide is missing a step with the newly launched Workgroup feature:
https://docs.aws.amazon.com/en_pv/athena/latest/ug/getting-started.html

When using Athena for the first time, one now needs to use Workgroup settings to define a S3 bucket else any SQL query will fail with a 400 error:

No output location provided. An output location is required either through the Workgroup result configuration setting or as an API input. (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: a15349df-ef33-4753-97b7-xxxxx).

I will try to repro with a completely clean account, it might also be a leftover.

**Comment by YernurSFU** [comment]
I had a same error. After setting a query_result_location in settings, it works fine,

**Comment by Pahtoe** [comment]
@wolruf and @YernurSFU thanks for the callout on this error. We'll revisit the getting started to get it updated for workgroups feature. Sorry for the inconvenience and the late reply; we've been down a writer in the Athena space and recently got staffed back up. We'll get this fixed soon.

**Comment by taammann** [comment]
We've updated the live [Getting Started](https://docs.aws.amazon.com/athena/latest/ug/getting-started.html) doc. Thanks for your help!
