### ISSUE TITLE
ST_Point does not work with WKT

### ISSUE THREAD

**Issue by JoaoCarabetta** [awsdocs/amazon-athena-user-guide#38]
In the list of [supported geospatial functions](https://docs.aws.amazon.com/athena/latest/ug/geospatial-functions-list.html) you can either instantiate a point as a pair of doubles or a wkt string using the function `ST_POINT`.

However, when I try to run the example, 

`SELECT ST_POINT('point (-74.006801 40.705220)');`

I get the following error:

```
An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 1:8: Unexpected parameters (varchar(28)) for function st_point. Expected: st_point(double, double)
```

On the other hand, if I try to run the same with `ST_POLYGON`, 

`SELECT ST_POLYGON('point (-74.006801 40.705220)');`

it seems to work fine.

So, I don't know if that is a problem in the documentation or Athena is not behaving as expected.

**Comment by Pahtoe** [comment]
@JoaoCarabetta First, sorry for the delay responding. We've been down a writer in Athena and recently staffed back up. It looks like your example above might be missing a comma between the values? Is that just a retype error?

**Comment by JoaoCarabetta** [comment]
Hi @Pahtoe, thanks for the response. This example comes directly from the [official documentation](https://docs.aws.amazon.com/athena/latest/ug/geospatial-functions-list.html).
And, I don't think that it is a comma error because [WKT standards](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry) do not expect commas between coordinates of the same point.

**Comment by Pahtoe** [comment]
Thanks for clarifying and sorry for that miss. The closest analog to our ST_Point function I believe is the [PostGIS ST_Point](https://postgis.net/docs/ST_Point.html). Comma I believe is required for syntax. I see what we did wrong now that you point it out. I'll fix it in doc's where we have syntax. Examples on that [same page](https://docs.aws.amazon.com/athena/latest/ug/geospatial-functions-list.html#constructors-functions) and [elsewhere](https://docs.aws.amazon.com/athena/latest/ug/geospatial-query-what-is.html) show the syntax with comma, so it *should* work that way. If it doesn't for you, LMK and I can get some help to dig in on it. Thanks again and sorry for the inconvenience.

**Comment by taammann** [comment]
The "alternative" syntax for ST_POINT('point (coordinate coordinate)') for passing in WKT values instead of comma-separated doubles no longer appears to be supported. We've removed that syntax option for ST_POINT from the documentation, so closing for now.
