### ISSUE TITLE
Upper limit on the number of partitions in a single "DROP PARTITION" request?

### ISSUE THREAD

**Issue by tj---** [awsdocs/amazon-athena-user-guide#40]
When I try dropping several partitions (= 35) in a single query, the operation fails with the following error:

**Error message**:
FAILED: SemanticException [Error 10006]: Partition not found

The drop request does have the "IF EXISTS" clause in it.
ALTER TABLE alpha_events_tracker DROP IF EXISTS PARTITION 

Sending a smaller number of partitions in a single request succeeds.

Sample Query Id: e7ef9cf5-46a4-4c62-8695-f0f8506f8d3a
**What could be the reason?** Is there an upper limit on the bytes that can be sent in a single request?

**Comment by taammann** [comment]
This sounds like a possible network latency issue, but that's just a guess on my part. I'd suggest contacting AWS Support (in the AWS console, click  __Support__, __Support Center__), or visit the [Amazon Athena Forum](https://forums.aws.amazon.com/forum.jspa?forumID=242) where you can post questions and find possible answers.
