### ISSUE TITLE
Using PrivateLink endpoints with ODBC

### ISSUE THREAD

**Issue by cthrasher** [awsdocs/amazon-athena-user-guide#41]
When using ODBC, the documentation mentions that you need to make sure that port 444 is open outbound for QueryResultStreaming. When connecting to Athena using a PrivateLink endpoint, the Security Group attached to that PrivateLink endpoint needs to be open to port 444 inbound or the query will fail with a "Connection Reset" error. I would recommend mentioning the need for the the inbound rule on the PrivateLink endpoint on the JDBC page:

https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

**Comment by taammann** [comment]
Hi cthrasher,
Thanks for your note - can you confirm whether your feedback applies to both the [ODBC](https://docs.aws.amazon.com/athena/latest/ug/connect-with-odbc.html) and [JDBC](https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html) pages?
Either way, we'll get the documentation updated as soon as we can.
Thanks,
Tim

**Comment by cthrasher** [comment]
Definitely JDBC, here's the error from my application team:

> An error occurred when executing the SQL command:
> select * from "athena-test".parquet_files
>  
> [Simba][AthenaJDBC](100123) An error has occurred. Exception during column initialization .Details: Unable to execute HTTP request: Connection reset [Execution ID: redacted]. [SQL State=HY000, DB Errorcode=100123]
> 1 statement failed.

The application they're using uses the same driver for both ODBC and JDBC, but I can't test whether the issue applies to ODBC. However, given that the ODBC page you linked to also says "Keep the port 444 open to outbound traffic", I assume that it does apply to ODBC as well.

**Comment by taammann** [comment]
Thanks - I'll follow up with the Athena feature team.

**Comment by taammann** [comment]
We've updated the docs, thanks.
