### ISSUE TITLE
STRING omitted from list of data_types

### ISSUE THREAD

**Issue by murrayw24** [awsdocs/amazon-athena-user-guide#47]
The example declares the data type of several columns as `STRING`. However, this is not listed above as one of the possible `data_type`s

**Comment by taammann** [comment]
Hi murrayw24,
It looks like you might be referring to the CREATE TABLE documentation page. If so, thanks for the catch! We'll get the page updated.

**Comment by murrayw24** [comment]
Yes, spot on. Thanks 🙂

**Comment by taammann** [comment]
No problem. Thanks for helping to improve the Athena documentation!
