### ISSUE TITLE
Button "Edit this page on GitHub" doesn't work at "Changing Athena Engine Versions" page.

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/amazon-athena-user-guide#55]
"Edit this page on GitHub" button on "Changing Athena Engine Versions" [page](https://docs.aws.amazon.com/athena/latest/ug/engine-versions-changing.html#engine-versions-troubleshooting) points at [404](https://github.com/awsdocs/amazon-athena-user-guide/tree/main/doc_source/engine-versions-changing.md).

**Comment by taammann** [comment]
Thanks, we'll get that fixed.

**Comment by taammann** [comment]
Done!
