### ISSUE TITLE
use Partition Projection for AWS Service Logs examples

### ISSUE THREAD

**Issue by mschfh** [awsdocs/amazon-athena-user-guide#58]
the examples in "Querying AWS Service Logs" create either a non-partitioned table or are using manual partitioning (e.g. CloudTrail/VPC flow logs), it would be great to have copy-paste-able templates for AWS service logs with commonly used partitions (region, date, ELB name/prefix)

**Comment by taammann** [comment]
mschfh,

Thanks for your suggestion - we'll take note of your request. 
Thanks for helping to improve the Athena documentation!

Athena Documentation Team
