### ISSUE TITLE
Documentation misrepresents syntax for bucket_by & partition_by in create table as

### ISSUE THREAD

**Issue by cbsmith** [awsdocs/amazon-athena-user-guide#59]
Extant documentation looks like this:

partitioned_by = ARRAY( [col_name,…])
Optional. An array list of columns by which the CTAS table will be partitioned. Verify that the names of partitioned columns are listed last in the list of columns in the SELECT statement.

bucketed_by( [bucket_name,…])
An array list of buckets to bucket data. If omitted, Athena does not bucket your data in this query.

But in fact the syntax for partition_by and bucketed_by clauses are the same and no use of parenthesis.

**Comment by taammann** [comment]
Thanks for the catch!
