### ISSUE TITLE
Unable to run the example at geospatial-example-queries

### ISSUE THREAD

**Issue by kaluzniacki** [awsdocs/amazon-athena-user-guide#62]
https://docs.aws.amazon.com/athena/latest/ug/geospatial-example-queries.html

I create the two tables and then I run the query, but the query fails with the error.

````
Your query has the following error(s):

SYNTAX_ERROR: line 5:7: Unexpected parameters (varbinary, Geometry) for function st_contains. Expected: st_contains(Geometry, Geometry) , st_contains(varchar, varchar) , st_contains(Geometry, varchar) , st_contains(varchar, Geometry)

This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 0b7713dd-77db-45aa-b7cc-5d5e83017245.
````

I will do some debugging, but I imagine this to be a bug in the documentation of the example.

Thanks!

**Comment by taammann** [comment]
Could you check the Athena engine version that you're using? Data input types for some geospatial functions changed between versions 1 and 2.

**Comment by kaluzniacki** [comment]
Maybe related to : https://docs.aws.amazon.com/athena/latest/ug/geospatial-functions-list-v2.html. 

https://docs.aws.amazon.com/athena/latest/ug/engine-versions-reference.html#engine-versions-reference-0002-changes-to-geospatial-functions


Yes - I am using 2. I see that there is specifically a difference.

**Comment by kaluzniacki** [comment]
This succeeds:
````SQL
SELECT counties.name,
        COUNT(*) cnt
FROM counties
CROSS JOIN earthquakes
WHERE ST_CONTAINS (ST_GeomFromLegacyBinary(counties.boundaryshape), ST_POINT(earthquakes.longitude, earthquakes.latitude))
GROUP BY  counties.name
ORDER BY  cnt DESC;
````

I will consider if I wan to have a workgroup just for Athena Engine 1 for some examples.  But I would respectfully request some additional text in the example pointing out the issue.

Thanks very mush for the amazingly quick response.

**Comment by kaluzniacki** [comment]
Further, I will read the additional documentation carefully, but on first read it is not clear to me how to determine if I have Legacy Binary or not.

**Comment by taammann** [comment]
Thanks for the catch! We'll update the example and add a note on the change in input requirements.
