### ISSUE TITLE
typo in documentation for setting up elb.

### ISSUE THREAD

**Issue by cloudsolarch** [awsdocs/amazon-athena-user-guide#78]
doc_source/elasticloadbalancer-classic-logs.md

input.regex has extra character in the documentation.  I spent couple of hours in troubleshooting the problem. Please remove the extra character.

Actual value for the input.regex:
'input.regex' = '([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*)[:-]([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-.0-9]*) (|[-0-9]*) (-|[-0-9]*) ([-0-9]*) ([-0-9]*) \\\"([^ ]*) ([^ ]*) (- |[^ ]*)\\\" (\"[^\"]*\") ([A-Z0-9-]+) ([A-Za-z0-9.-]*)$' )

It should have been, without extra ")" at the end of the value.
'input.regex' = '([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*)[:-]([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-.0-9]*) (|[-0-9]*) (-|[-0-9]*) ([-0-9]*) ([-0-9]*) \\\"([^ ]*) ([^ ]*) (- |[^ ]*)\\\" (\"[^\"]*\") ([A-Z0-9-]+) ([A-Za-z0-9.-]*)$'

**Comment by taammann** [comment]
Thanks for the catch! We'll get it updated.
