### ISSUE TITLE
Likely missing permission "glue:GetDatabases"

### ISSUE THREAD

**Issue by RajasGujarathi** [awsdocs/amazon-athena-user-guide#81]
### **Describe**
We are trying to make use of the [Connecting to Amazon Athena with ODBC](https://docs.aws.amazon.com/athena/latest/ug/connect-with-odbc.html) to connect to AWS DynamoDB via AWS Athena

When we are trying to provide limited permission(s) to the AWS IAM User we are referring to the [Fine-grained access to databases and tables in the AWS Glue Data Catalog](https://docs.aws.amazon.com/athena/latest/ug/fine-grained-access-to-glue-resources.html#full-access-to-default-db-per-region) but we encounter the following error

### **Error**
> FAILED!
>
>[Simba][Athena] (1040) An error has been thrown from the AWS Athena client. Error Message: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:User: AWS_IAM_User_ARN is not authorized to perform: glue:GetDatabases on resource: arn:aws:glue:\*:\*:catalog because no identity-based policy allows the glue:GetDatabases action (Service: AmazonDataCatalog; Status Code: 400; Error Code: AccessDeniedException; Request ID: <Request Id>; Proxy: null)) [Execution ID: <Execution Id>]

### **Proposal**
In the documentation, [Fine-grained access to databases and tables in the AWS Glue Data Catalog](https://docs.aws.amazon.com/athena/latest/ug/fine-grained-access-to-glue-resources.html#full-access-to-default-db-per-region), `glue:GetDatabases` needs to be present in addition to existing permissions.

Can someone help confirm?

**Comment by taammann** [comment]
Thanks for bringing this to our attention and your subsequent pull request.
