### ISSUE TITLE
No arm64 macOS ODBC driver?

### ISSUE THREAD

**Issue by MattCowgill** [awsdocs/amazon-athena-user-guide#83]
This page lists ODBC drivers available for Athena: https://github.com/awsdocs/amazon-athena-user-guide/blob/main/doc_source/connect-with-odbc.md 

The macOS driver (labelled OS X) appears to be an x_86 build. It would be useful to have a native arm64 build for the newer Apple Silicon Macs.

**Comment by taammann** [comment]
Thanks for your suggestion. I've passed it on to the Athena team.

**Comment by MattCowgill** [comment]
I guess this is not going to get fixed. Very frustrating!

**Comment by taammann** [comment]
Frustration understood, and apologies for the inconvenience. I'd also suggest emailing <a href='ma&#105;lto&#58;at&#37;68%6&#53;%6E%61-fe&#101;d%&#54;2&#97;%63%&#54;B&#64;&#97;%&#54;Da%7Aon&#46;&#99;%6&#70;m'>a&#116;&#104;e&#110;&#97;&#45;f&#101;e&#100;back&#64;&#97;&#109;a&#122;on&#46;com</a> directly with your feature request. Presumably something will happen if there is enough demand.

**Comment by MattCowgill** [comment]
Will do, thanks
