### ISSUE TITLE
[docs] Add port open guide in JDBC & ODBC

### ISSUE THREAD

**Issue by seunggabi** [awsdocs/amazon-athena-user-guide#97]
I connected Tableau and Athena Connector by JDBC drivers
I opened port (443, 444) about athena, glue, sts.

So, I added this guide.
If you don't understand my words.
Please modify my documents. (more readability)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
